### DISCUSSION TITLE
Changing the name of the tabs e.g Archives -> Timeline

### DISCUSSION THREAD

**Discussion by ali14hasnain** [cotes2020/jekyll-theme-chirpy#1297] [Q&A] [answered]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Built from `jekyll-theme-chirpy`

### Description

Basically the title. 
Would appreciate the help, if its not allowed please lmk, thank you.

### Operations you have already tried

-

**Comment by zhang-nianqiang** [comment, marked as answer]
I think u can use the `en.yml` file in `_data/locales/` and then change them. 
Like this:

```
tabs:
  # format: <filename_without_extension>: <value>
  home: Home
  categories: Categories
  tags: Tags
  archives: Archives -> Timeline
  about: About
```
