### DISCUSSION TITLE
make the code snippet scrollable

### DISCUSSION THREAD

**Discussion by Brainor** [cotes2020/jekyll-theme-chirpy#1319] [Ideas]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### What is the topic?

Sharing tips and tricks

### Description

When writing a post that contains a huge chunk of code, sometimes it's kind of ugly to see the whole code.

And here is an approach that I use to make the code block scrollable.

1. copy the `jekyll-theme-chirpy.scss` file according to the [instruction](https://chirpy.cotes.page/posts/getting-started/#customizing-stylesheet)
2. add this codeblock to end of the file
    ```scss
    div.scroll > .highlight {
        overflow-y: auto;
        height: 400px;
    }
    ```
3. when writing the code block in the post, just add `{: .scroll }` at the end of the code block like this
    <pre>```python
    # large chunk of code
   ```
   {: .scroll}</pre>

The rendered content looks like this
![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/5477995/699126a5-3b42-40fd-b35a-0c4fb0816a08)

I don't think this is needed by most of the users, so instead of a PR I post the approach here  in case anyone also needs it.

**Comment by Rootjhon** [comment]
### Is a better idea?
1. Configure `height` value
2. When it exceeds the `height` and **automatically** becomes scrollable

**Reply by Brainor** [reply]
Good idea, and I can modify the `jekyll-theme-chirpy.scss` as below:
```scss
---
---

@import 'main';

/* append your custom style below */
$max-lines: 15; // max lines of code to be scrolled

.highlight {
    overflow-y: auto;
    max-height: $max-lines * 1em;
}
```
where `15` is the number of lines I can manully set.

---

When writing a post likes this: 
<pre><code>```python
print('a')
print('a')
print('a')
print('a')
print('a')
print('a')
print('a')
print('a')
print('a')
print('a')
print('a')
print('a')
print('a')
print('a')
print('a')
print('a')
print('a')
```
not scrollable when lines are less than 15
```python
print('a')
print('a')
print('a')
```
first empty line of code causes misalignment
```python


print('a')
print('a')
print('a')
```</code></pre>
it produces 
![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/5477995/54755223-bdb6-44a1-b41e-b09f39864023)
