### DISCUSSION TITLE
how can I change the next button hover color?

### DISCUSSION THREAD

**Discussion by wakhoo** [cotes2020/jekyll-theme-chirpy#1427] [Q&A] [answered]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Built from `jekyll-theme-chirpy`

### Description

<img width="523" alt="스크린샷 2023-12-23 16 06 40" src="https://github.com/cotes2020/jekyll-theme-chirpy/assets/40779092/a78a34e2-cc85-4f18-9924-eb31e306edfa">
I want to change this color but it's hard to find for me..Can somebody help me?

### Operations you have already tried

I already look for _sass/colors/typography-light.scss and _sass/layout/post.scss but I couldn't find the right one.

**Comment by kungfux** [comment, marked as answer]
This style comes from the external place, so there is no definition for it in this repository.

You can change it by adding overridden styles in `assets\css\jekyll-theme-chirpy.scss` as following:

```scss
.btn:hover {
  background-color: red !important;
}

.btn.btn-outline-primary {
  &:not(.disabled):hover {
    border-color: red !important;
  }
}
```

Here is the result:
![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/10548881/2d191ba1-f061-4f4b-8059-f09844c2fd74)
