### DISCUSSION TITLE
How to change the Trending Tags hover color?

### DISCUSSION THREAD

**Discussion by SimoneFelici** [cotes2020/jekyll-theme-chirpy#1505] [Q&A] [answered]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Description

I edited all the thing that I wanted, Apart from the Trending Tags, when I hover on a trending tag is blue, how do I change that? 
I tried searching for it but I got nothing.

### Operations you have already tried

I search the _sass folder to find something useful, I did not found anything

**Comment by kungfux** [comment, marked as answer]
This style comes from the external place, so there is no definition for it in this repository.

You can change it by adding overridden styles in `assets\css\jekyll-theme-chirpy.scss` as following:

```scss
.btn:hover {
  background-color: #36bcf7 !important;
}

.btn.btn-outline-primary {
  &:not(.disabled):hover {
    border-color: #36bcf7 !important;
  }
}
```

Here is the result:
![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/10548881/5acefbd6-e301-473f-ac86-1b654b6ad1cf)

Please don't track my IP :D
