### DISCUSSION TITLE
Chirpy blog and Google Search Console?

### DISCUSSION THREAD

**Discussion by nyhryan** [cotes2020/jekyll-theme-chirpy#1514] [Q&A] [answered]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Description

Hello, I have been trying to add my chirpy-starter blog to google search, but it seems to only register the main blog homepage, but not individual posts. Does anyone have this issue? Do I need to do something else than just adding main blog entrypoint to google seach console? (`nyhryan.github.io` for my case)  It's been almost a month that I am trying to figure this out. 

### Operations you have already tried

I tried adding some category folder to Google search console, but it made only that category folder show up in google search, not individual posts IN that category folder.

**Comment by kungfux** [comment, marked as answer]
I do not have a comprehensive answer for you, but I want you to know that you are not alone.

Here is some information I would like to share.

I like the answer already [mentioned](https://github.com/cotes2020/jekyll-theme-chirpy/discussions/1176#discussioncomment-6745372) that

> (Google Search) Typically you'll get about 200 or so results on 10 or so pages.  To get ranked, you either have to be a very popular site or an (AI) verifiable expert with a lot of authority.
>
> With so much content, Google often just doesn't index it all anymore. It just knows it'll never have to show things for which it already has so many results.

This problem is not unique to Google, where I have 2 indexed pages after 2 months. I'm currently playing with Bing and it's in no hurry to index my blog either.

Personally, I decided to let other search engines know of my existence by modifying my `_config.yml` as follows:

```yml
webmaster_verifications:
  google: # fill in your Google verification code
  bing: # fill in your Bing verification code
  alexa: # fill in your Alexa verification code
  yandex: # fill in your Yandex verification code
  baidu: # fill in your Baidu verification code
  facebook: # fill in your Facebook verification code
```

This will not solve the problem with Google, but it will probably increase the chances of making your blog more visible to others.

---

Also, you raised a good question in another thread:

> How long does it take for posts to get indexed? I've been waiting ages to get the posts indexed. I want to make sure posts get indexed eventually. I want to just write posts as much I want, not having to worry about my posts not being exposed to the internet.

I'm not sure about Google at this point, but Bing has a feature called [IndexNow](https://www.bing.com/indexnow) that you can trigger from your site's publishing pipeline to archive what you suggest.

---

Also, do not rely solely on web searches. An even better way to increase traffic might be to submit to some popular publishing portals and social networking sites. Even having links there will increase your blog's authority through cross mentions, as far as I know.
