### DISCUSSION TITLE
Share buttons

### DISCUSSION THREAD

**Discussion by krilovskiy** [cotes2020/jekyll-theme-chirpy#1552] [Q&A] [answered]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Description

Hello. I'v successfully deployed blog to [github pages](https://github.com/krilovskiy/krilovskiy.github.io) but when I'm trying to share post in telegram from [here](https://krilovskiy.com/posts/methods-on-t/), i'v got link like this
`https://t.me/share/url?url=%2Fposts%2Fmethods-on-t%2F&text=%D0%9E%D0%B1%D1%8A%D1%8F%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5%20%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D0%BE%D0%B2%20%D1%83%20%D1%82%D0%B8%D0%BF%D0%B0%20T%20%D0%B8%D0%BB%D0%B8%20*T%20-%20%D0%92%D0%BB%D0%B0%D0%B4%20%D0%9A%D1%80%D1%8B%D0%BB%D0%BE%D0%B2%D1%81%D0%BA%D0%B8%D0%B9`

url parameter is broken. How can i fix this? 

### Operations you have already tried

I'v uncommented telegram share params 
```
platforms:
  - type: Telegram
    icon: "fab fa-telegram"
    link: "https://t.me/share/url?url=URL&text=TITLE"

  - type: Twitter
    icon: "fa-brands fa-square-x-twitter"
    link: "https://twitter.com/intent/tweet?text=TITLE&url=URL"

  - type: Facebook
    icon: "fab fa-facebook-square"
    link: "https://www.facebook.com/sharer/sharer.php?title=TITLE&u=URL"

  - type: Linkedin
    icon: "fab fa-linkedin"
    link: "https://www.linkedin.com/sharing/share-offsite/?url=URL"
```
