### DISCUSSION TITLE
How to add captions (such as below images) but anywhere?

### DISCUSSION THREAD

**Discussion by mattpopovich** [cotes2020/jekyll-theme-chirpy#1669] [Q&A] [answered]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Description

I would like to add captions to things other than images, such as blocks of code or iframes. 

### Operations you have already tried

Looking at previous posts I've created, I used to add `<my-caption>Caption text here</my-caption>`. I'm not sure why that worked but I do remember it working. It no longer works and just renders as normal text.

Has this feature been removed? Changed?

**Comment by kungfux** [comment, marked as answer]
I'm not sure about `<my-caption>` existence and I didn't find it in the code.

There are ways to do this using custom styles.

Make sure you copy `assets\css\jekyll-theme-chirpy.scss` from this repository to yours.

## Option 1. Using <em> tag in markdown

Modify `assets\css\jekyll-theme-chirpy.scss` to add styles as following

```css
em {
  display: block;
  text-align: center;
  font-style: normal;
  font-size: 80%;
  padding: 0;
  color: #6d6c6c;
}
```

and then use in posts like

```markdown
<em>This is my caption</em>
```

## Option 2. By specifying a class with styles

Modify `assets\css\jekyll-theme-chirpy.scss` to add styles as following

```css
.caption {
  display: block;
  text-align: center;
  font-style: normal;
  font-size: 80%;
  padding: 0;
  color: #6d6c6c;
}
```

and then use in posts like

```markdown
This is my caption.
{: .caption }
```
