### DISCUSSION TITLE
feat(sidebar): Add friends link in the side bar

### DISCUSSION THREAD

**Discussion by huanyushi** [cotes2020/jekyll-theme-chirpy#1677] [Ideas]
Hello everyone, I'm here to share a customization to the sidebar - adding friend links.

## How to achieve?
Add the following code to `_includes/sidebar.html` (before the button at the bottom of the sidebar.):

```html
  <!-- friend links -->
  {% if site.data.friends %}
      {% include friends.html %}
  {% endif %}
```

Then create a new file `_includes/friends.html`:
```html
<!-- friend links -->
<div class="friends">
     <hr style="border: 1px solid ">
    <p><i class="fas fa-user-friends"></i><span>FRIENDS</span></p>
    <ul>
      {% for friend in site.data.friends %}
      <li><a href="{{friend.href}}">{{friend.title}}</a></li>
      {% endfor %}
    </ul>
</div>
```

The relevant style design can be added to `assets/css/jekyll-theme-chirpy.scss`:

```scss
#sidebar .friends {
    padding-left: 2.5rem;
    padding-right: 1.25rem;
    width: 100%;
    margin-bottom: 1.5rem;
}
#sidebar .friends p {
    color: var(--site-subtitle-color);
    font-family: inherit;
    font-weight:600;
    font-size: 95%;
}
#sidebar .friends p i {
    opacity: 0.8;
    margin-right: 1.5rem;
}
#sidebar .friends p span {
    letter-spacing: 0.2px;
    opacity: 0.9;
}
#sidebar .friends ul {
    color:var(--site-subtitle-color);
    font-size:95%;
    opacity: 0.95;
    margin-bottom: 0rem;
}
#sidebar .friends ul li {
    margin-bottom: 0.4rem;
    opacity: 0.9;
}
```

Note that here I borrowed the color variable name from `subtitle`, of course, you can also define a new variable to control the color in light and dark modes.

Then you can add friend links in `_data/friends.yml`, e.g. :

```yml
  - title: "Title1"
    href: "https://example.com/"
  - title: "Title2"
    href: "https://example.com/"
  - title: "Title3"
    href: "https://example.com/"
  - title: "Title4"
    href: "https://example.com/"
```

## Effect
See the following figures and my [BLOG](https://huanyushi.github.io/):

<p align='center'>
<img src='https://github.com/cotes2020/jekyll-theme-chirpy/assets/100574401/560280a1-ba0b-4cdd-bd96-5eb095455535' width="32%">
<img src='https://github.com/cotes2020/jekyll-theme-chirpy/assets/100574401/bb335aab-8319-46f4-9e51-1ebe05b55369' width="32%">
<img src='https://github.com/cotes2020/jekyll-theme-chirpy/assets/100574401/053dae9e-70bc-4a66-acd4-ac6e3f960d56' width="32%">
</p>

## Note
This method is only suitable for adding a **small** number of friend links, otherwise, they will occupy space at the bottom buttons. If you need to add a **large** number of friend links, my suggestion is to create a new file "friends.md" in `_tabs` and place all the friend links there.
