### DISCUSSION TITLE
The blog structure suddenly changed.

### DISCUSSION THREAD

**Discussion by ykdman** [cotes2020/jekyll-theme-chirpy#1721] [Q&A] [answered]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Built from `jekyll-theme-chirpy`

### Description

Hi! i'm using 'chirpy' github blog Theme

- When i Was Push blog to my github, and actions Complete,
- Watch my blog Status
![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/83913024/30038221-13ce-4f86-802e-a7913120bf3a)

- suddenly th errors comming my blog
- please helf

### Operations you have already tried

- try on bash : npm run buid
- run  'bundle exec jekyll serve' multiple times

**Comment by kungfux** [comment, marked as answer]
This happens because some scripts cannot be loaded due to certificate expiration. Please see #1718.

**Reply by ykdman** [reply]
I Read the issue and set '_config.yml' following [chirpy-static-assets](https://github.com/cotes2020/chirpy-static-assets)

in description
i need to set '_config.yml'

```yml
assets:
  self_host:
    enabled: true # boolean, keep empty means false
    # specify the Jekyll environment, empty means both
    # only works if `assets.self_host.enabled` is 'true'
    env: "production" # [development | production]
```

it's right?
