### DISCUSSION TITLE
Change Hamburger menu to 'X' on mobile

### DISCUSSION THREAD

**Discussion by ghost** [cotes2020/jekyll-theme-chirpy#1868] [Q&A] [answered]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Description

![Screenshot_20240721-192628](https://github.com/user-attachments/assets/03109105-4be7-4095-8b45-dd3e255fe744)
As you can see the screenshot above, on mobile when we open the menu it still stays as hamburger icon.
Is there a way to change it to an 'X' icon?

### Operations you have already tried

I keep looking through the codes but haven't found anything.

**Comment by kungfux** [comment, marked as answer]
Override the style in `assets/css/jekyll-theme-chirpy.scss` as following:

```css
body[sidebar-display] {
  .fa-bars:before,
  .fa-navicon:before {
    content: '\58' !important;
  }
}
```

[Here](https://fontawesome.com/search?q=x&o=r) you can find other icons if you prefer to change to something else.
