### DISCUSSION TITLE
How to add the ability for readers to comments on my posts?

### DISCUSSION THREAD

**Discussion by 0xShun** [cotes2020/jekyll-theme-chirpy#2037] [Q&A]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Description

I want a feature for readers to add comments on my posts

### Operations you have already tried

I have tried different tutorials in disqus and giscus but the tutorials there all seem to have steps that doesn't fit with this theme. Like the _layouts/post.html I can't seem to find it in my project directory. Are there other ways to add commenting feature?

**Comment by kungfux** [comment]
Please check [_config.yml](https://github.com/cotes2020/chirpy-starter/blob/main/_config.yml#L110). You just need to choose comments provider and specify it, then configure options related to that provider.

```yml
comments:
  # Global switch for the post-comment system. Keeping it empty means disabled.
  provider: # [disqus | utterances | giscus]
  # The provider options are as follows:
  disqus:
    shortname: # fill with the Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances settings › https://utteranc.es/
  utterances:
    repo: # <gh-username>/<repo>
    issue_term: # < url | pathname | title | ...>
  # Giscus options › https://giscus.app
  giscus:
    repo: # <gh-username>/<repo>
    repo_id:
    category:
    category_id:
    mapping: # optional, default to 'pathname'
    strict: # optional, default to '0'
    input_position: # optional, default to 'bottom'
    lang: # optional, default to the value of `site.lang`
    reactions_enabled: # optional, default to the value of `1`
```
