### DISCUSSION TITLE
Can't see comments section

### DISCUSSION THREAD

**Discussion by 5o1z** [cotes2020/jekyll-theme-chirpy#2082] [Q&A] [answered]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Description

I have set what is needed for the comment section in config.yml but it still does not show up on the web

### Operations you have already tried

I have enabled discussion for my repo
And set the config.yml like this:
```yml
comments:
  active: giscus  # The global switch for posts comments, e.g., 'disqus'.  Keep it empty means disable
  # The active options are as follows:
  disqus:
    shortname:  # fill with the Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances settings › https://utteranc.es/
  utterances:
    repo: # <gh-username>/<repo>
    issue_term: # < url | pathname | title | ...>
  # Giscus options › https://giscus.app
  giscus:
    repo: 5o1z/5o1z.github.io # <gh-username>/<repo>
    repo_id: R_kgDONW53cQ
    category: Comments
    category_id: DIC_kwDONW53cc4Cky9v
    mapping: # optional, default to 'pathname'
    input_position: top # optional, default to 'bottom'
    lang: # optional, default to the value of `site.lang`
    reactions_enabled: 1 # optional, default to the value of `1`
```
Am I do something wrong?

**Comment by kungfux** [comment, marked as answer]
Hey @5o1z .

Be sure to check your `_config.yml` as you are using the latest version of Chirpy with an outdated configuration template. You need to specify [provider](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/_config.yml#L112) instead of `active`.

```yml
comments:
  # Global switch for the post-comment system. Keeping it empty means disabled.
  provider: # [disqus | utterances | giscus]
```
