### DISCUSSION TITLE
My GoatCounter dont work

### DISCUSSION THREAD

**Discussion by maxXx1** [cotes2020/jekyll-theme-chirpy#2084] [Q&A] [answered]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Description

I tried to insert my GoatCounter ID, it loads the stats correctly, but doesn't display them on the page. It just loads endlessly in the post.

![image](https://github.com/user-attachments/assets/db416cf0-6588-4c85-9c54-4c100f4a99c4)

```yaml
# Web Analytics Settings
analytics:
  google:
    id: # fill in your Google Analytics ID
  goatcounter:
    id: 1982 # fill in your GoatCounter ID
  umami:
    id: # fill in your Umami ID
    domain: # fill in your Umami domain
  matomo:
    id: # fill in your Matomo ID
    domain: # fill in your Matomo domain
  cloudflare:
    id: # fill in your Cloudflare Web Analytics token
  fathom:
    id: # fill in your Fathom Site ID

# Page views settings
pageviews:
  provider: goatcounter # now only supports 'goatcounter'
```

### Operations you have already tried

- I changed my ID to a number
- Allow adding visitor counts on your website
- Allow data colection of individual pageviews
- Add my domain and github.io domain that can embed GoatCounter in a frame

### Anything else?

You can check out my entire repository on my github profile, I recently upgraded to a new version of the theme.

Thank you all so much for your help.
