### DISCUSSION TITLE
Trying to understand if I should use environment secrets

### DISCUSSION THREAD

**Discussion by CyRamos** [cotes2020/jekyll-theme-chirpy#2088] [Q&A]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Description

Hey guys, 
I just installed Chirpy 2 days ago and it already seem wonderful. 
I connected it to subdomain and want to implement Webmaster, Web Analytics & HTML Tags verification (Tag manager).
- For HTML Tag - it seems I should implement the code google provide (head & body parts) at  `_site/index.html` am I right or is there another place for this?
- Webmaster & Web Analytics - I wonder if I should use GitHub Environment Secrets for storing the keys for security purposes, because I noticed `_site` is under `.gitignore` ...just wondering if it's still necessary for your opinion. 
Thanks :) 

### Operations you have already tried

None, there are only general questions above.

### Anything else?

None.

**Comment by kungfux** [comment]
The whole idea of Jekyll is to build a site for you from markdown files, so you have no reason to change anything in the `_site` folder that will be overwritten by the site build.

Use `_config.yml` to specify verification codes

```yml
# Site Verification Settings
webmaster_verifications:
  google: # fill in your Google verification code
  bing: # fill in your Bing verification code
  alexa: # fill in your Alexa verification code
  yandex: # fill in your Yandex verification code
  baidu: # fill in your Baidu verification code
  facebook: # fill in your Facebook verification code
```

There is no need to worry about security as they are accessible to everyone as part of the `index.html` code.
