### DISCUSSION TITLE
TOC not displaying in starter

### DISCUSSION THREAD

**Discussion by Hrovatin** [cotes2020/jekyll-theme-chirpy#2095] [Q&A] [answered]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Description

I am building my page locally and TOC is not shown. 

Is this expected and does it mean that it will show up once page is published on github? - Since I did not manage to run `npm` due to missing files in starter.

### Operations you have already tried

- Updated to 7.2.1
- Unsuccessfully tried to run `npm`, but seems to be not intended on starter as per https://github.com/cotes2020/jekyll-theme-chirpy/wiki/Upgrade-Guide#upgrade-the-fork

**Comment by SoumyaK4** [comment]
@Hrovatin have you tried clearing all jekyll cache before rebuilding?

**Comment by kungfux** [comment]
> does it mean that it will show up once page is published on github?

TOC should work on local build.

I would suggest to check `_config.yml` to make sure TOC is enabled globally which is by default but still.

```yml
# boolean type, the global switch for TOC in posts.
toc: true

defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
```

Then, make sure you have no errors in browser console when you open the post.
