### DISCUSSION TITLE
Custom CSS not loading

### DISCUSSION THREAD

**Discussion by seaque** [cotes2020/jekyll-theme-chirpy#2158] [Q&A]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Description

I have been using this theme for a long time, I used to be able to generate from `chirpy-starter` and had customized
`_data/origin/cors.yml`, `assets/css/jekyll-theme-chirpy` and had been using `_saas/variables-hook.scss` to deal easily with version updates, now these files are simply ignored upon both publishing to GH pages and local Jekyll serve.

### Operations you have already tried

- Start with clean repository.
- Enable/disable self host assets.

### Anything else?

Ruby 3.2.2 (2023-03-30 revision e51014f9c0) 
Jekyll 4.3.4

**Comment by cotes2020** [comment]
The `_saas/variables-hook.scss` has been deprecated in #2052 of [v7.2.0][v720].

[v720]: https://github.com/cotes2020/jekyll-theme-chirpy/releases/tag/v7.2.0

If you want to achieve the same effect on the latest starter (v7.2.0+), please follow the example below to override the default values:

In file `assets/css/jekyll-theme-chirpy.scss`:

```diff
---
---

+@use 'abstracts/variables' with ( 
+  $sidebar-width: 250px 
+);

@use 'main
{%- if jekyll.environment == 'production' -%}
  .bundle
{%- endif -%}
';

/* append your custom style below */
```

**Reply by seaque** [reply]
Sorry, I update rarely so must've missed that one. 

Still though, can't get rid of this error.
```
Error: expected "$".
  ╷
3 │   $font-family-base: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol, Noto Color Emoji;
  │                             ^
  ╵
```

Only one font without comma works. Which is far than ideal.

Same error even with default ones
```
Error: expected "$".
  ╷
3 │ $font-family-base: 'Source Sans Pro', 'Microsoft Yahei', sans-serif !default;
  │                                       ^
  ╵
```

**Reply by iSpeakNerd** [reply]
hey @cotes2020 i appended custom scss for custom icons as font using what you suggested, but it made my whole site render weird on remote, on local it looked fine. any ideas here?

edit: solved in https://github.com/cotes2020/jekyll-theme-chirpy/discussions/2345#discussioncomment-12811297

tl;dr
```diff
- {%- if jekyll.environment == ' production ' -%}
+ {%- if jekyll.environment == 'production' -%}
```

![image](https://github.com/user-attachments/assets/5a017ff7-18a3-4e0b-99a0-9b06973e936f)

here's what i did

1.  follow steps to create custom icons as fonts from https://github.com/cotes2020/jekyll-theme-chirpy/discussions/1763#discussioncomment-9490407 
2.  overwrite default [chirpy theme css file](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/assets/css/jekyll-theme-chirpy.scss) with appended css from icomoon solution, inspired by coates https://github.com/cotes2020/jekyll-theme-chirpy/discussions/2158#discussioncomment-11710805
```scss
---
---

@use 'main
{%- if jekyll.environment == ' production ' -%}
  .bundle
{%- endif -%}
';

/* append your custom style below */

@font-face {
  font-family: 'icomoon';
  src: url('/assets/fonts/icomoon.eot?weotyf');
  src: url('/assets/fonts/icomoon.eot?weotyf#iefix') format('embedded-opentype'),
    url('/assets/fonts/icomoon.ttf?weotyf') format('truetype'),
    url('/assets/fonts/icomoon.woff?weotyf') format('woff'),
    url('/assets/fonts/icomoon.svg?weotyf#icomoon') format('svg');
  font-weight: normal;
  font-style: normal;
  font-display: block;
}

[class^='icon-'],
[class*=' icon-'] {
  font-family: 'icomoon' !important;
  speak: never;
  font-style: normal;
  font-weight: normal;
  font-variant: normal;
  text-transform: none;
  line-height: 1;

  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

.icon-fc-arch:before {
  content: '\e900';
}
```
3. add custom contact links in `_data/contact.yml` following suggestion by @SoumyaK4 https://github.com/cotes2020/jekyll-theme-chirpy/discussions/2172#discussioncomment-11774968 
```yml
- type: farcaster
  icon: "icon-fc-arch"
  url: "https://warpcast.com/ispeaknerd"
```
