### DISCUSSION TITLE
How do I add custom social links in chirpy?

### DISCUSSION THREAD

**Discussion by iSpeakNerd** [cotes2020/jekyll-theme-chirpy#2172] [Q&A] [answered]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Description

Would like to add custom social links with icons in the sidebar footer and author on posts. 

### Operations you have already tried

I found a few jekyll references but most are for the default theme Minima rather than Chirpy specifically. 
- https://old.reddit.com/r/Jekyll/comments/1co7fke/deleted_by_user/ 
- this discussion is specifically for icons https://github.com/cotes2020/jekyll-theme-chirpy/discussions/1763
- https://blog.jakelee.co.uk/adding-new-social-media-link-to-minima/

The blog post references `footer.html` and `social.html` neither of which are in chirpy starter. I see `social:` section of `_config.yml` for adding links (which doesn't seem to change the sidebar footer?) but how do i add the svg for the links in the footer and authorship as well as associate them to the correct url?

### Anything else?

my current socials settings in `_config.yml`
```md
social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: iSpeakNerd
  # email: # change to your email address
  links:
    # The first element serves as the copyright owner's link
    - https://twitter.com/ispeak_nerd # change to your Twitter homepage
    - https://github.com/ispeaknerd # change to your GitHub homepage
    - https://warpcast.com/ispeaknerd # change to your Warpcast homepage
    # Uncomment below to add more social links
    # - https://www.facebook.com/username
    - https://www.linkedin.com/in/ispeaknerd
    - https://paragraph.xyz/@ispeaknerd.eth
```

**Comment by SoumyaK4** [comment]
You can add them in `_data/contact.yml` for sidebar social links.

For modifying footer look in `_includes/footer.html`

**Reply by iSpeakNerd** [reply]
thanks for replying! I don't have an _includes folder so I should just create it and the footer.html file within?

**Reply by SoumyaK4** [reply]
Check here https://github.com/cotes2020/jekyll-theme-chirpy

**Comment by iSpeakNerd** [comment, marked as answer]
what finally worked for me:
1.  follow steps to create custom icons as fonts from https://github.com/cotes2020/jekyll-theme-chirpy/discussions/1763#discussioncomment-9490407 
2.  overwrite default [chirpy theme css file](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/assets/css/jekyll-theme-chirpy.scss) with appended css from icomoon solution, inspired by coats https://github.com/cotes2020/jekyll-theme-chirpy/discussions/2158#discussioncomment-11710805
```scss
---
---

@use 'main
{%- if jekyll.environment == 'production' -%}
  .bundle
{%- endif -%}
';

/* append your custom style below */

@font-face {
  font-family: 'icomoon';
  src: url('/assets/fonts/icomoon.eot?weotyf');
  src: url('/assets/fonts/icomoon.eot?weotyf#iefix') format('embedded-opentype'),
    url('/assets/fonts/icomoon.ttf?weotyf') format('truetype'),
    url('/assets/fonts/icomoon.woff?weotyf') format('woff'),
    url('/assets/fonts/icomoon.svg?weotyf#icomoon') format('svg');
  font-weight: normal;
  font-style: normal;
  font-display: block;
}

[class^='icon-'],
[class*=' icon-'] {
  font-family: 'icomoon' !important;
  speak: never;
  font-style: normal;
  font-weight: normal;
  font-variant: normal;
  text-transform: none;
  line-height: 1;

  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

.icon-fc-arch:before {
  content: '\e900';
}
.icon-fc-arch-inverted:before {
  content: '\e901';
}
```
3. add custom contact links in `_data/contact.yml` following suggestion by @SoumyaK4 https://github.com/cotes2020/jekyll-theme-chirpy/discussions/2172#discussioncomment-11774968 
```yml
- type: farcaster
  icon: "icon-fc-arch"
  url: "https://warpcast.com/ispeaknerd"
```

Note: cannot change icon names after downloading from icomoon, so make sure your svg files are named however you want to reference them

**Reply by iSpeakNerd** [reply]
It looks fine on local serve but displays weird when merged and served by github pages
~~![image](https://github.com/user-attachments/assets/e88df02f-af65-4d36-a0f2-fe87439f8971)~~

edit: fixed with @tis-starlight's [suggestion](https://github.com/cotes2020/jekyll-theme-chirpy/discussions/2172#discussioncomment-11867909)

**Reply by SoumyaK4** [reply]
You're making it too complicated....
You should follow my previous suggestion....
The only changes you need as per your original post should be in `_data/contact.yml`
Try looking in other's codes who use chirpy...
[Example](https://github.com/SoumyaK4/chirpy-starter-mods)

**Reply by tis-starlight** [reply]
> It looks fine on local serve but displays weird when merged and served by github pages ![image](https://private-user-images.githubusercontent.com/96841384/403572903-e88df02f-af65-4d36-a0f2-fe87439f8971.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzcxMjM5NzcsIm5iZiI6MTczNzEyMzY3NywicGF0aCI6Ii85Njg0MTM4NC80MDM1NzI5MDMtZTg4ZGYwMmYtYWY2NS00ZDM2LWEwZjItZmU4NzQzOWY4OTcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE3VDE0MjExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkMWZkMmIzZmFkYjE1MWE3MDgxZWIwYzQ1ODU4YzdhMWFlNDZiNTBiYTRhYjRmMDQxY2JmYmUyMjdjY2ZkMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qj-XfNHPUfQsVywT_V9gderroPcK336SLWGLYDxbHR8)

---
Remove the extra spaces around `production` in the `jekyll-theme-chirpy.scss` file and don’t use Prettier to format the document.


```diff
- {%- if jekyll.environment == ' production ' -%}
+ {%- if jekyll.environment == 'production' -%}
```

**Reply by iSpeakNerd** [reply]
@SoumyaK4 that works if you are using an icon served by font awesome, i see in your linked `_data/contact.yml`

```yml
- type: website
  icon: "fas fa-s"
  url: "https://soumyak4.in"
  noblank: true
```
`icon: "fas fa-s"` but i have a custom svg not found in fa, hence the extra stuff
