### DISCUSSION TITLE
Google Site verification (Google Search console)

### DISCUSSION THREAD

**Discussion by 0xKrat0s** [cotes2020/jekyll-theme-chirpy#2214] [Q&A]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Description

I want too add my blog in google search console. But iam not able to verify the site using TXT records. 

### Operations you have already tried

I have added TXT record in _config.yml file.

` google_site_verification: imSGv4Gj6q-ymfSPGK4HPlF8GPffwpbcz2K9O5_pOmM`

### Anything else?

Iam getting this error in google console:

```
Ownership verification failed
Verification method:
Domain name provider
Failure reason:
We couldn't find your verification token in your domain's TXT records. Sometimes DNS changes can take a while to appear. Please wait a few hours, then reopen your property in Search Console. If verification fails again, try adding a different DNS TXT record.
```

**Comment by SoumyaK4** [comment]
```
# Site Verification Settings
webmaster_verifications:
  google: # fill in your Google verification code
  bing: # fill in your Bing verification code
  alexa: # fill in your Alexa verification code
  yandex: # fill in your Yandex verification code
  baidu: # fill in your Baidu verification code
  facebook: # fill in your Facebook verification code
```

This is in the `_config.yml` @0xKrat0s
