### DISCUSSION TITLE
How to add baseurl on author's social links in _config.yml

### DISCUSSION THREAD

**Discussion by rafisics** [cotes2020/jekyll-theme-chirpy#2239] [Q&A]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Built from `jekyll-theme-chirpy`

### Description

Let's say, my website is hosted on `https://github.com/username/website`, I want to know how to configure it so that clicking the author name would lead to the page `https://username.github.io/website/about/`. 

How can I do it without using the absolute link? 

### Operations you have already tried

I'm using with the `baseurl` set in `_config.yml` as follows:
```
url: "https://username.github.io" 
baseurl: "/website"
social:
  name: Me
  email: emaili@example.com
  links:
    - "{{ site.baseurl }}/about/"
```
When I serve it locally, it directs to the page:
```
http://127.0.0.1:4000/website/%7B%7B%20site.baseurl%20%7D%7D/about/
```
Or depending on the current page, suppose I am at `http://127.0.0.1:4000/website/posts/` it renders as:
```
http://127.0.0.1:4000/website/posts/%7B%7B%20site.baseurl%20%7D%7D/about/
```
