### DISCUSSION TITLE
How to enable ToC on the layout `page`?

### DISCUSSION THREAD

**Discussion by rafisics** [cotes2020/jekyll-theme-chirpy#2241] [Q&A]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Description

I would like to enable ToC on both the `page` and `post` layouts. Here's the [template](https://github.com/rafisics/website-theme/tree/dee125cf8bb51e3c96af9454a28f13b067c04cd6) I am using.

### Operations you have already tried

I tried with changing the [_layouts/page.html](https://github.com/rafisics/website-theme/blob/dee125cf8bb51e3c96af9454a28f13b067c04cd6/_layouts/page.html) in the following way:

```
---
layout: default
refactor: true
panel_includes:
  - toc
---

{% include lang.html %}

{% include toc-status.html %}

<article class="px-1" data-toc="{{ enable_toc }}">
  {% if page.layout == 'page' or page.collection == 'pages' %}
  <header>
    <h1 data-toc-skip>{{ page.title }}</h1>
    {% if page.description %}
    <blockquote class="prompt-info">{{ page.description }}</blockquote>
    {% endif %}

    <div class="post-meta text-muted">
      {% if page.image %}
        {% capture src %}src="{{ page.image.path | default: page.image }}"{% endcapture %}
        {% capture class %}class="preview-img{% if page.image.no_bg %}{{ ' no-bg' }}{% endif %}"{% endcapture %}
        {% capture alt %}alt="{{ page.image.alt | xml_escape | default: "Preview Image" }}"{% endcapture %}

        {% if page.image.lqip %}
          {%- capture lqip -%}lqip="{{ page.image.lqip }}"{%- endcapture -%}
        {% endif %}

        <div class="mt-3 mb-3">
          <img {{ src }} {{ class }} {{ alt }} w="1200" h="630" {{ lqip }}>
          {%- if page.image.alt -%}
            <figcaption class="text-center pt-2 pb-2">{{ page.image.alt }}</figcaption>
          {%- endif -%}
        </div>
      {% endif %}
    </div>
  </header>

  {% if enable_toc %}
    <div id="toc-bar" class="d-flex align-items-center justify-content-between invisible">
      <span class="label text-truncate">{{ page.title }}</span>
      <button type="button" class="toc-trigger btn me-1">
        <i class="fa-solid fa-list-ul fa-fw"></i>
      </button>
    </div>

    <button id="toc-solo-trigger" type="button" class="toc-trigger btn btn-outline-secondary btn-sm">
      <span class="label ps-2 pe-1">{{- site.data.locales[lang].panel.toc -}}</span>
      <i class="fa-solid fa-angle-right fa-fw"></i>
    </button>

    <dialog id="toc-popup" class="p-0">
      <div class="header d-flex flex-row align-items-center justify-content-between">
        <div class="label text-truncate py-2 ms-4">{{- page.title -}}</div>
        <button id="toc-popup-close" type="button" class="btn mx-1 my-1 opacity-75">
          <i class="fas fa-close"></i>
        </button>
      </div>
      <div id="toc-popup-content" class="px-4 py-3 pb-4"></div>
    </dialog>
  {% endif %}

    <div class="content">
      {{ content }}
    </div>
  {% else %}
    {{ content }}
  {% endif %}
</article>
```

and tested with following change in [_pages/about.md](https://github.com/rafisics/website-theme/blob/dee125cf8bb51e3c96af9454a28f13b067c04cd6/_pages/about.md):

```
---
layout: page
title: About
permalink: /about/
---

> Add Markdown syntax content to file `_pages/about.md`{: .filepath } and it will show up on this page.
{: .prompt-tip }

# H1 

## H2

### H3 

```
The ToC is not appearing. How to resolve it?

**Comment by rafisics** [comment]
The steps I have followed to enable ToC on the `page` layout:

 1. Import the directory `_javascript/`, the files `package.json`, `purgecss.js`, and `rollup.config.js` from the [jekyll-theme-chirpy](https://github.com/cotes2020/jekyll-theme-chirpy/tree/7d4d35cd10109e78d60fbb6b25a9b205f780ad63) repo.
 2. Add `initToc()` to `_javascript/page.js`, just like `_javascript/post.js`: 

```javascript
// _javascript/page.js

import { basic, initSidebar, initTopbar } from './modules/layouts';
import {
  loadImg,
  imgPopup,
  initClipboard,
  initToc,
  loadMermaid
} from './modules/components';

loadImg();
imgPopup();
initSidebar();
initTopbar();
initClipboard();
iniToc();
loadMermaid();
basic();

 ```
3. Regenerate the local build:
```bash
npm install
npm run build
bundle exec jekyll clean 
bundle exec jekyll serve
```
4. Update GitHub action workflow `.github/workflows/pages-deploy.yml`: 
```yml
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: "Build and Deploy"

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4.2.0
        with:
          node-version: '22.x' # Use Node.js 22.x LTS version

      - name: Install Dependencies (npm)
        run: npm install

      - name: Build assets
        run: npm run build # Run the build process for assets

      - name: Setup Ruby
        # https://github.com/ruby/setup-ruby/releases/tag/v1.207.0
        uses: ruby/setup-ruby@4a9ddd6f338a97768b8006bf671dfbad383215f4
        with:
          ruby-version: '3.1' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
          
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        # Outputs to the './_site' directory by default
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
        # Automatically uploads an artifact from the './_site' directory by default
        uses: actions/upload-pages-artifact@v3

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
``` 
---
To enable ToC *globally* on every `page`, I have added the following to `_config.yml`:

```yml
toc: true 

defaults:
  - scope:
      path: ""
    values:
      layout: post
      toc: true # Display TOC column in posts.
      permalink: /:categories/:title/
  - scope:
      path: "" 
      type: pages
    values:
      layout: page
      toc: true # Display TOC column in pages.
```

**Reply by rafisics** [reply]
But maybe I am doing something wrong here, I am not sure. It seems leading me to a new issue: PWA popup is not appearing (https://github.com/cotes2020/jekyll-theme-chirpy/discussions/2258).

**Reply by jsurrea** [reply]
Hey @rafisics, this was really helpful. Thanks a lot!

**Reply by rafisics** [reply]
You are welcome. Can you let me know if you are getting the same issue (https://github.com/cotes2020/jekyll-theme-chirpy/discussions/2258) now?

**Reply by jsurrea** [reply]
> You are welcome. Can you let me know if you are getting the same issue (#2258) now?

Unfortunately I'm facing the same issue as you :/

**Reply by rafisics** [reply]
> Unfortunately I'm facing the same issue as you :/

I haven't figured out the solution yet. But I am guessing it's caused by the `npm` commands I added to the GitHub action workflow, which is needed for the ToC. Kindly inform me if you find any way to resolve it.

**Reply by rafisics** [reply]
> Unfortunately I'm facing the same issue as you :/

check out this one (https://github.com/cotes2020/jekyll-theme-chirpy/discussions/2241#discussioncomment-12741177) to resolve the issue.

**Reply by rafisics** [reply]
Also, u might have noticed that I moved to `pages` from `tabs`, not sure if that's the reason. 
Check this as well: https://github.com/rafisics/pwa-test/commit/7d7da03ade200d3f9358b81f7dcd03ba5c44eca5

**Comment by lotusk08** [comment]
Try this:
1. Page layout
```html
---
layout: default
panel_includes:
 - toc
---

{% include lang.html %}
{% include toc-status.html %}

<article class="px-1" data-toc="{{ enable_toc }}">
  {% if page.layout == 'page' or page.collection == 'tabs' %}
    {% assign tab_key = page.title | downcase %}
    {% assign title = site.data.locales[lang].tabs[tab_key] | default: page.title %}
    <h1 data-toc-skip class="dynamic-title">
      {{ title }}
    </h1>

  {% if enable_toc %}
    <div id="toc-bar" class="d-flex align-items-center justify-content-between invisible">
      <span class="label text-truncate">{{ page.title }}</span>
      <button type="button" class="toc-trigger btn me-1">
        <i class="fa-solid fa-list-ul fa-fw"></i>
      </button>
    </div>

    <button id="toc-solo-trigger" type="button" class="toc-trigger btn btn-outline-secondary btn-sm">
      <span class="label ps-2 pe-1">{{- site.data.locales[lang].panel.toc -}}</span>
      <i class="fa-solid fa-angle-right fa-fw"></i>
    </button>

    <dialog id="toc-popup" class="p-0">
      <div class="header d-flex flex-row align-items-center justify-content-between">
        <div class="label text-truncate py-2 ms-4">{{- page.title -}}</div>
        <button id="toc-popup-close" type="button" class="btn mx-1 my-1 opacity-75">
          <i class="fas fa-close"></i>
        </button>
      </div>
      <div id="toc-popup-content" class="px-4 py-3 pb-4"></div>
    </dialog>
  {% endif %}

    <div class="content">
      {{ content }}
    </div>
  {% else %}
    {{ content }}
  {% endif %}
</article>

```
3. JS
Adjust toc.js to support page instead of post only:
_javascript/page.js:
```javascript
import { basic, initTopbar } from './modules/layouts';
import {
  loadImg,
  initToc,
  imgPopup,
  initClipboard,
  loadMermaid
} from './modules/components';

loadImg();
initToc();
imgPopup();
initTopbar();
initClipboard();
loadMermaid();
basic();
```

4. Front matter
a. For config.yml:
```yml:
defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /:title
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title
      toc: true
```
b. For page - that needs TOC. Insert to front matter:
```yml
---
# the default layout is 'page'
toc: true
---
```

After all, run `npm run build` to compile javascript, you'll get the new version of `assets/js/dist/page.min.js` before building/deploying your site.
Check this if you need to see the difference when I update this feature: [Compare](https://github.com/lotusk08/lotusk08.github.io/commit/e4b0460b5b6d52c2cc805dbb7afef76e4f56b799)
