### DISCUSSION TITLE
Help with `htmlproofer` Errors: Missing References and Invalid Internal Links

### DISCUSSION THREAD

**Discussion by rafisics** [cotes2020/jekyll-theme-chirpy#2291] [Q&A]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Built from `jekyll-theme-chirpy`

### Description

I'm currently using the following workflow on this [site](https://github.com/rafisics/chirpy-test/tree/b45d45f2e4ae007e07ea55d52fdbf425a05f8202):
```
name: "Build and Deploy"
on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # submodules: true
          # If using the 'assets' git submodule from Chirpy Starter, uncomment above
          # (See: https://github.com/cotes2020/chirpy-starter/tree/main/assets)

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      - name: Build site
        run: bundle exec jekyll b -d "_site${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: "production"

      - name: Test site
        run: |
          bundle exec htmlproofer _site \
            \-\-disable-external \
            \-\-ignore-urls "/^http:\/\/127.0.0.1/,/^http:\/\/0.0.0.0/,/^http:\/\/localhost/"

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "_site${{ steps.pages.outputs.base_path }}"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

```
Here `htmlproofer` is used to check my Jekyll site after building it, and I'm encountering [several errors](https://github.com/rafisics/chirpy-test/actions/runs/13751389819/job/38452782129) that I'm struggling to understand and resolve. Here are the two main types of issues I’m facing:

### 1. Missing `href` references in `<a>` tags
I'm seeing the following errors in my site files:
```
'a' tag is missing a reference
```
This is happening across multiple pages in my `_site` directory, such as:
- `404.html`
- `about/index.html`
- `blogging/tutorial/customize-the-favicon/index.html`
- and others.

It seems that `htmlproofer` is flagging `<a>` tags that are missing `href` attributes. I’ve checked my templates and content files, but I can’t seem to figure out why these links are missing references. Does anyone have suggestions for how to fix this?

### 2. Invalid internal links
I’m also getting warnings about internal links that point to non-existent pages:
```
internally linking to /chirpy-test/blogging, which does not exist
```
For example:
- `blogging/tutorial/write-a-new-post/index.html` is linking to `../text-and-typography/`
- Several tags and categories pages are linking to paths like `/chirpy-test/getting-started/` that don’t exist.

Could someone guide me on how to fix these broken internal links or why they might be incorrectly pointing to these paths?

### Operations you have already tried

I’ve tried the following solutions:
- Double-checking my `_config.yml` for any misconfigurations.
- Ensuring all necessary files exist in the correct locations.
- Rebuilding the site to make sure the changes are reflected.

But I’m still facing these errors.
