### DISCUSSION TITLE
add a custom directory structure to site root.

### DISCUSSION THREAD

**Discussion by ebmarquez** [cotes2020/jekyll-theme-chirpy#2369] [Q&A]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Built from `jekyll-theme-chirpy`

### Description

I'm looking to add a specific directory structure to share my pem public key.  This is to support an automation for my Home Assistant service.  I need to add the following to the site root.
.well-known/appspecific/com.tesla.3p.public-key.pem

Goal:

open a url to the following `http://mysite/.well-known/appspecific/com.tesla.3p.public-key.pem` and download the pem file.  It's required to have the following structure.

I tried doing the following which worked in my branch before I merged. 
In my _config.yml

```yaml
defaults:
  ...
  - scope:
      path: .well-known/appspecific
    values:
      layout: none
include:
  - .well-known
```

This change also included the pem file and directory structure being added at the root of the repo.

Is there something else I should be doing?

      

### Operations you have already tried

added to the config.yaml

```yaml
defaults:
  ...
  - scope:
      path: .well-known/appspecific
    values:
      layout: none
include:
  - .well-known
```
With the pem file.
