### ISSUE TITLE
Why my toc doesn't work?为什么我的目录显示不出来？

### ISSUE THREAD

**Issue by Venompool888** [cotes2020/jekyll-theme-chirpy#1001]
I have already read ur [article](https://chirpy.cotes.page/posts/write-a-new-post/#table-of-contents).  
The toc in my config is true here.  
![image](https://user-images.githubusercontent.com/94547252/233838699-1b6d2167-f7da-4917-a86b-3d96baf7bd1c.png)  
But it still doesn't work.I'm sure that my posts are all edit in right way,as u can see it.
![截图 2023-04-23 07-55-29](https://user-images.githubusercontent.com/94547252/233838750-fcb1637e-7fe5-47f5-81eb-db9452cf2529.png)
![image](https://user-images.githubusercontent.com/94547252/233838915-97561af7-0615-4af5-84a8-6feaaaf8b76f.png)
Maybe it's because I'm using Chinese?

**Comment by gezhaoyou** [comment]
有相同的问题 sad, fifo.site

**Comment by gezhaoyou** [comment]
Have same issue😢: https://fifo.site

**Comment by gezhaoyou** [comment]
I found why, at you blog root, run 
`npm install && npm run build`
see [https://github.com/cotes2020/jekyll-theme-chirpy/wiki/Upgrade-Guide#upgrade-the-fork](https://github.com/cotes2020/jekyll-theme-chirpy/wiki/Upgrade-Guide#upgrade-the-fork)

**Comment by gezhaoyou** [comment]
My site now ok. run `npm install && npm run build` at site root dir, then `bundle update`
see https://github.com/cotes2020/jekyll-theme-chirpy/wiki/Upgrade-Guide#upgrade-the-fork

**Comment by lextm** [comment]
Duplicate to #951

**Comment by MezereonXP** [comment]
If you use the GitHub action to deploy your site automatically, you could follow my config:

```yaml
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          ruby-version: '3.1' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Build with Jekyll
        # Outputs to the './_site' directory by default
        run: |
          npm install --global yarn
          yarn install
          yarn build
          bundle update
          JEKYLL_ENV=production bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production
      - name: Upload artifact
        # Automatically uploads an artifact from the './_site' directory by default
        uses: actions/upload-pages-artifact@v1

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

```
