### ISSUE TITLE
An error occurred: giscus is not installed on this repository 

### ISSUE THREAD

**Issue by Bistard** [cotes2020/jekyll-theme-chirpy#1153]
**NOTE:** Before you start, the following should be completed.

- Read [Wiki][wiki] to understand the usage and the correct effect of functional design.
- Make sure no [similar issue(including closed ones)][issues] exists.
- Make sure the bug is found in the latest code of the `master` branch.

[wiki]: https://github.com/cotes2020/jekyll-theme-chirpy/wiki
[issues]: https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue

## Describe the bug
My blog site says an error while I am enabling giscus: `An error occurred: giscus is not installed on this repository `
![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/38385498/7ce585fb-ca96-4593-b646-14480c436d90)

## To Reproduce

1. I installed `giscus` in Github and gives the permissions to all the repositories.
2. I enabled the Discussion section for my repository.
3. I complete comment-related configuration in `_config.yml` as following:
```yml
comments:
  # The global switch for posts comments, e.g., 'disqus'.  Keep it empty means disable
  active: giscus
  # The active options are as follows:
  disqus:
    shortname: # https-bistard-github-io # fill with the Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances settings › https://utteranc.es/
  utterances:
    repo: # <gh-username>/<repo>
    issue_term: # < url | pathname | title | ...>
  # Giscus options › https://giscus.app
  giscus:
    repo: https://github.com/Bistard/Bistard.github.io
    repo_id: R_kgDOKBe4Bg
    category: Announcements
    category_id: DIC_kwDOKBe4Bs4CYQsZ
    mapping: pathname # optional, default to 'pathname'
    input_position: top # optional, default to 'bottom'
    lang: en # optional, default to the value of `site.lang`
    reactions_enabled: 1 # optional, default to the value of `1`
```
4. The error shows below at every blog post on the website.

## Expected behavior
A functional `giscus` comment section.

## Environment

| Command                           | Version |
|-----------------------------------|---------|
| `ruby -v`                         |      ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-linux]   |
| `gem -v`                          |     3.4.17    |
| `bundle -v`                       |   Bundler version 2.4.17      |
| `bundle exec jekyll -v`           |    jekyll 4.3.2     |
| `bundle info jekyll-theme-chirpy` |    jekyll-theme-chirpy (6.1.0)     |

## Additional context

Here is my website link: https://bistard.github.io/posts/Microservice-Driven-Architecture/
