### ISSUE TITLE
Links broken when jekyll-archives.permalinks.tag/category is changed (regardless of rebuild)

### ISSUE THREAD

**Issue by Valinwolf** [cotes2020/jekyll-theme-chirpy#1164]
## Describe the bug

Theme does not acknowledge alternative permalinks as configured in _config.yml

## To Reproduce

Change
```
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
```
to
```
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /cuisines/:name/
    category: /cities/:name/
```

## Expected behavior

After a rebuild, category links should point to `/cities/{category name/city}` and tag links should point to `/cuisines/{tag name/cuisine type}`

## What Actually Happens

404 error because the  links are hardcoded to "expected" permalink of `/categories/*` and `/tags/*`.

## Environment

| Command                           | Version |
|-----------------------------------|---------|
| `ruby -v`                         |  3.22       |
| `gem -v`                          |  3.4.18       |
| `bundle -v`                       |  2.4.18       |
| `bundle exec jekyll -v`           |  4.3.2       |
| `bundle info jekyll-theme-chirpy` |  6.1.0       |
| Operating System |  Fedora 38       |
| Web Server |  NGINX 1.24.0       |

### Desktop

- OS: Fedora 38
- Browser: GNU IceCat 102.13.0esr

### Smartphone

- Device: iPhone 14 Pro Max
- OS: iOS 16.6
- Browser: Safari

## Additional context

I'm trying to make the wording and permalinks more suited for my blog by setting making tags "cuisines" and categories "cities". I made a separate language file en_food.yml and changed the wording, and updated the permalinks in _config.yml. The language file change worked perfectly, but the permalink change did not work as expected as it changed it on the file system, but not the generated links.
