### ISSUE TITLE
Github secret is not working inside _config.yml

### ISSUE THREAD

**Issue by msrajawat298** [cotes2020/jekyll-theme-chirpy#1166]
**NOTE:** Before you start, the following should be completed.

- Read [Wiki][wiki] to understand the usage and the correct effect of functional design.
- Make sure no [similar issue(including closed ones)][issues] exists.
- Try to find the answer on [Jekyll Forum][forum] and [StackOverflow][stack_overflow].

[wiki]: https://github.com/cotes2020/jekyll-theme-chirpy/wiki
[issues]: https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue
[forum]: https://talk.jekyllrb.com/
[stack_overflow]: https://stackoverflow.com/questions/tagged/jekyll

## Description

I have create secrete inside GitHub repo environment secret and pass the value like this
```
  giscus:
    repo: ${{ secrets.REPO }}
    repo_id: ${{ secrets.REPO_ID }}
    category: General
    category_id: ${{ secrets.CAT_ID }}
    mapping: pathname # optional, default to 'pathname'
    input_position: # optional, default to 'bottom'
    lang: # optional, default to the value of `site.lang`
    reactions_enabled: # optional, default to the value of `1`
```
