### ISSUE TITLE
Use Bootstrap's npm package and Sass variables

### ISSUE THREAD

**Issue by ImDati** [cotes2020/jekyll-theme-chirpy#1270]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### Is your feature request related to a problem? Please describe

It makes it harder to change Bootstrap color variables for things like "trending tags" hover color.
Instead of using sass variables with variables-hook, I need to change the colors on my own with css.

### Describe the solution you'd like

Use Bootstrap NPM package instead of embedding in html and refactor the theme so it usse Bootstrap's variables.

### Additional context

Thats how I change it currently, by adding `bootstrap-override.scss` for example in `/_scss/`:
```scss
.btn-outline-primary {
  --bs-btn-color: #38AA38;
  --bs-btn-border-color: #38AA38;
  --bs-btn-hover-color: #fff;
  --bs-btn-hover-bg: #38AA38;
  --bs-btn-hover-border-color: #38AA38;
  --bs-btn-focus-shadow-rgb: 13,253,110;
  --bs-btn-active-color: #fff;
  --bs-btn-active-bg: #38AA38;
  --bs-btn-active-border-color: #38AA38;
  --bs-btn-active-shadow: inset 0 3px 5px rgba(0, 0, 0, 0.125);
  --bs-btn-disabled-color: #38AA38;
  --bs-btn-disabled-bg: transparent;
  --bs-btn-disabled-border-color: #38AA38;
  --bs-gradient: none;
}

.btn.btn-outline-primary {
  &:not(.disabled):hover {
    border-color: #329932 !important;
  }
}
```
