### ISSUE TITLE
Build Failure with Ruby 3.x due to google-protobuf Gem Error in GitHub Actions

### ISSUE THREAD

**Issue by winxuan** [cotes2020/jekyll-theme-chirpy#1429]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Describe the bug

When using the pages-deploy.yml GitHub Actions workflow with the default ruby-version: 3, the build process fails during bundle install due to an error related to the installation of the google-protobuf gem.

### Steps To Reproduce

I just submitted an article, probably because Ruby 3.3.0 was released

### Expected Behavior

The GitHub Actions build should complete successfully without errors during the bundle install process.

### Environment

GitHub Actions

### Anything else?

The build succeeds when explicitly setting ruby-version: 3.2.2 in the workflow file. This version change seems to resolve the issue with the google-protobuf gem installation.
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

**Comment by puppylpg** [comment]
same error :cry: ruby 3.3.0 released yesterday

**Comment by winxuan** [comment]
> same error 😢 ruby 3.3.0 released yesterday

I modified
.github/workflows/pages-deploy.yml
Probably around line 42 to line 47
`````````````````````````````````````````````````
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
````````````````````````````````````````````````````````````````
change ruby-version: 3   -->   ruby-version: 3.2.2

Specify to the 3.2.2 version before ruby was released

it works fine
