### ISSUE TITLE
'a' tag is missing a reference error during build if all of the social links are commented out

### ISSUE THREAD

**Issue by seaque** [cotes2020/jekyll-theme-chirpy#1493]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Describe the bug

If you happen to comment out all the links in config social links section,

```
social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: your_full_name
  email: example@domain.com # change to your email address
  links:
    # The first element serves as the copyright owner's link
    # - https://twitter.com/username # change to your twitter homepage
    # - https://github.com/username # change to your github homepage
    # Uncomment below to add more social links
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username
```

you will get **`'a' tag is missing a reference`**, the error seemed to be fix in #1403, but can still be seen. This behaviour may be unintended, maybe nobody is supposed to comment out all the links. But I spent good old chunk of my time trying the reason, so in either way of it being a bug or a user error, I wanted to note it out.

### Steps To Reproduce

1. Fork `jekyll-theme-chirpy` or `generate chirpy-starter`.
2. Comment out all social links in _config.yml
3. Try building the site with GitHub actions.

### Expected Behavior

Site building successfully without any social links.

### Environment

- Ruby: 3.2.2 
- Jekyll: 4.3.3 
- Chirpy: 6.4.2
