### ISSUE TITLE
Customize font-familiy with Chirpy Starter template?

### ISSUE THREAD

**Issue by BlandAlpha** [cotes2020/jekyll-theme-chirpy#1597]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### Is your feature request related to a problem? Please describe

I'm using Chirpy Starter's template and everything worked smoothly. But I cannot find any `sass file` or `config` option to set font-family. Is there a hidden way to do this or it's just not possible right now?

### Describe the solution you'd like

A poosible way to customize font-family without switching to fork option.

**Comment by pavel-perina** [comment]
I solved this by editing assets/css/jekyll-theme-chirpy.scss and adding the following lines (example):
However I assume that these modifications are not future proof.

```css
/* append your custom style below */
@import url('https://fonts.bunny.net/css2?family=IBM+Plex+Mono&family=IBM+Plex+Sans&family=IBM+Plex+Serif&display=swap');

body {
	font-family: "IBM Plex Sans", sans-serif;
}
#search-results a,h5,h4,h3,h2,h1 {
	font-family: "IBM Plex Serif", serif;
}
pre, code, kbd, samp {
	font-family: "IBM Plex Mono", monospace;
}
```
