### ISSUE TITLE
Website does not update when new one is built/deployed

### ISSUE THREAD

**Issue by classicrocker883** [cotes2020/jekyll-theme-chirpy#1816]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Describe the bug

After updating and pushing to my fork, when it would build and deploy, I used to see a prompt show up saying "A new version is available. Update" and clicking Update would refresh the webpage to the new version. However, that isn't the case anymore.

I'm not sure what happened or why that changed, but the only way around this is either open the webpage in something like Incognito, or delete cookie/history.

### Steps To Reproduce

1. Push changes
2. Go to website
3. Observe a popup saying a new version is available  
if not, then *this* is the issue.

### Expected Behavior

I expect the webpage to either update automatically to the new version upon refresh, or at the very least prompt me to update the page.

### Environment

- Ruby: ruby 3.3.2 (2024-05-30 revision e5a195edf6) [x64-mingw-ucrt]
- Jekyll: jekyll 4.3.3
- Chirpy:   * jekyll-theme-chirpy (7.0.1)
        Summary: A minimal, responsive, and feature-rich Jekyll theme for technical writing.
        Homepage: https://github.com/cotes2020/jekyll-theme-chirpy
        Documentation: https://github.com/cotes2020/jekyll-theme-chirpy/#readme
        Source Code: https://github.com/cotes2020/jekyll-theme-chirpy
        Wiki: https://github.com/cotes2020/jekyll-theme-chirpy/wiki
        Bug Tracker: https://github.com/cotes2020/jekyll-theme-chirpy/issues
        Path: C:/Users/Andrew/Documents/PlatformIO/classicrocker883.github.io

### Anything else?

[classicrocker883.github.io](https://classicrocker883.github.io/)

**Comment by cotes2020** [comment]
I think you should learn to read the docs.

**Comment by classicrocker883** [comment]
even with starting over fresh, it doesn't show the "Update" for a new version.

maybe it has something to do with this being depreciated?
```bash
npm run build        

> jekyll-theme-chirpy@7.0.1 build
> concurrently npm:build:*

(node:22796) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

**Comment by classicrocker883** [comment]
how about this?
do I disable this and that should help?
```yml
pwa:
  enabled: true # the option for PWA feature (installable)
  cache:
    enabled: true # the option for PWA offline cache
    # Paths defined here will be excluded from the PWA cache.
    # Usually its value is the `baseurl` of another website that
    # shares the same domain name as the current website.
    deny_paths:
```

**Comment by Gaur4vGaur** [comment]
@classicrocker883 I am not sure if you manage to resolve this and but I did it by `concurrently`. The command is as below

Run the below command in your local 
`npm install -g concurrently`

and then 
`npm run build`

and finally add these to your repo
`git add assets/js/dist _sass/dist -f`

Putting it here in case anyone else is facing the issue

**Comment by classicrocker883** [comment]
what I did was in **_config.yml**
just add path to `deny_paths:`
```yml
pwa:
  enabled: true # The option for PWA feature (installable)
  cache:
    enabled: true # The option for PWA offline cache
    # Paths defined here will be excluded from the PWA cache.
    # Usually its value is the `baseurl` of another website that
    # shares the same domain name as the current website.
    deny_paths:
      # - "/example"  # URLs match `<SITE_URL>/example/*` will not be cached by the PWA
```

however, I think things are updating as it should, but I haven't tested for the path I included to be denied cache.
