### ISSUE TITLE
Support for keybase.io for contacting

### ISSUE THREAD

**Issue by tejavegesna** [cotes2020/jekyll-theme-chirpy#1927]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### Is your feature request related to a problem? Please describe

Display Way to reach out using https://keybase.io/ instead of just emails

### Describe the solution you'd like

Example to reach out which can be displayed as a widget or icon 
https://keybase.io/tejavegesna

**Comment by kungfux** [comment]
Modify `_data/contact.yml` file to add the configuration for keybase:

```yml
- type: keybase
  icon: "fa-brands fa-keybase"
  url: "https://keybase.io/tejavegesna"
```
