### ISSUE TITLE
_data/origin/basic.yml has incorrect filenames for dayjs.

### ISSUE THREAD

**Issue by CRCinAU** [cotes2020/jekyll-theme-chirpy#1935]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Describe the bug

The file `_data/origin/basic.yml` contains the following for dayjs:

```yml
dayjs:
  js:
    common: /assets/lib/dayjs/dayjs.min.js
    locale: /assets/lib/dayjs/locale/en.js
    relativeTime: /assets/lib/dayjs/plugin/relativeTime.js
    localizedFormat: /assets/lib/dayjs/plugin/localizedFormat.js
```

if the following is specified in `_config.yml`, then these files seem to break.
```yml
assets:
  self_host:
    enabled: yes
    env: production
```

The files on disk seem to end up as:
```
$ find assets/lib/dayjs/
assets/lib/dayjs/
assets/lib/dayjs/dayjs.min.js
assets/lib/dayjs/locale
assets/lib/dayjs/locale/en.min.js
assets/lib/dayjs/plugin
assets/lib/dayjs/plugin/localizedFormat.min.js
assets/lib/dayjs/plugin/relativeTime.min.js
```

I'm confused as to why this doesn't seem to match here:
https://github.com/cotes2020/chirpy-static-assets/tree/main/dayjs/plugin

Given the `.gitmodule` file references the following:
```
[submodule "assets/lib"]
	path = assets/lib
	url = https://github.com/cotes2020/chirpy-static-assets.git
```

and this seems to be up to date, how / where are these files getting minimised?

If I disable the self_host options, then these same assets load from the CDNs correctly with the filenames expected.

### Steps To Reproduce

I build the site with the following script:

```bash
#!/bin/bash
export JEKYLL_ENV=production
export RUBY_YJIT_ENABLE=1

echo; echo " - Updating bundles..."
bundle update
git submodule update

echo; echo " - Cleaning current data..."
bundle exec jekyll clean

echo; echo " - Building site..."
bundle exec jekyll build

if [ ! -d "_site" ]; then
    echo "Error: Site build failed..."
    exit 1
fi
```

### Expected Behavior

That files on disk match files in the CDN with the minified versions if applicable.

### Environment

- Ruby: ruby 3.3.4 (2024-07-09 revision be1089c8ec) [x86_64-linux]
- Jekyll: jekyll 4.3.3
- Chirpy:
* jekyll-theme-chirpy (7.1.0)
Summary: A minimal, responsive, and feature-rich Jekyll theme for technical writing.
Homepage: https://github.com/cotes2020/jekyll-theme-chirpy
Documentation: https://github.com/cotes2020/jekyll-theme-chirpy/#readme
Source Code: https://github.com/cotes2020/jekyll-theme-chirpy
Wiki: https://github.com/cotes2020/jekyll-theme-chirpy/wiki
Bug Tracker: https://github.com/cotes2020/jekyll-theme-chirpy/issues
Path: /home/<username>/.local/share/gem/ruby/gems/jekyll-theme-chirpy-7.1.0
