### ISSUE TITLE
Dark/Light mode for preview image

### ISSUE THREAD

**Issue by MindStudioOfficial** [cotes2020/jekyll-theme-chirpy#2253]
### Checklist

- [x] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### Is your feature request related to a problem? Please describe

Currently preview image only supports one image ignoring the current color scheme.

### Describe the solution you'd like

I propose submitting different preview images based on the dark/light mode:

```
---
image: 
  path-dark: /path/to/dark-image
  path-light: /path/to/light-image
  lqip-dark: /path/to/dark-image-lqip
  lqip-light: /path/to/light-image-lqip
---
```

or

```
---
image: 
  path:
    light: ...
    dark: ...
  lqip:
    light: ...
    dark: ...
---
```
