### ISSUE TITLE
Blog title image not printed in the blog post itself

### ISSUE THREAD

**Issue by PaleSkinnySwede** [cotes2020/jekyll-theme-chirpy#2458]
### Checklist

- [x] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### Is your feature request related to a problem? Please describe

The problem is that images at the beginning of a blog post takes up too much space.

### Describe the solution you'd like

It would be cool if the image linked in the Front Matter wasn't printed in the post itself and only in the list on the Home page. Perhaps using a `visible:` property?

```
---
title: TITLE
date: YYYY-MM-DD HH:MM:SS +/-TTTT
categories: [TOP_CATEGORY, SUB_CATEGORY]
tags: [tag, another tag, a third tag]
image:
  path:
  alt:
  visible: false
---
```

In that case, I could have a 19:10 formatted image in the blog list on the Home page, and a 3:1 cropped in the post itself.
