### ISSUE TITLE
How can I add an option for Instagram on the side bar?

### ISSUE THREAD

**Issue by Greg-T8** [cotes2020/jekyll-theme-chirpy#500]
I'm not sure if this would be a feature request or a question, so I'll start with a question.

I'd like to introduce an icon for my Instagram profile in the side bar.  

I introduced a block of code for Instagram in _contact.yml, but I'm not clear on the process to include the image file.  What steps should I take to introduce the image file?

I'm just getting started with Jekyll and Chirpy, so assume starter knowledge with some coding experience but no front-end experience.

Thx!

**Comment by mattpopovich** [comment]
Yes, add the below to your `_data/contact.yml` file:
```yml
- type: instagram
  icon: 'fab fa-instagram'
  url: https://www.instagram.com/mattcracklepops/
  ```
