### ISSUE TITLE
5.2.0 broke preview images for me

### ISSUE THREAD

**Issue by joshjohanning** [cotes2020/jekyll-theme-chirpy#625]
## Checklist

- [x] I have read the [tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I found the bug on the latest code of the `master` branch.

## Describe the bug

Preview images aren't working for me after updating to 5.2.0. In fact, the whole `class="preview-img bg"` class is gone from the page source.

It appears this is the [commit](https://github.com/cotes2020/jekyll-theme-chirpy/commit/b8d1bcd3dea0abd1afef7ef154a4501fbb18938d#diff-88e83e5d0edb4286d0e35534fa9f49405a4ef6724137b468772a31183cb43a3fL14) that affects me. 

Specifically, the change from `page.image.src` to `page.image.path`.  

Changing it back to `page.image.src` does bring preview images back for me.

I have confirmed this is true with a fresh copy by testing this with a fresh clone of this repository.

### To Reproduce

Post header to reproduce - the preview image disappears.

```yml
---
title: 'Test'
author: Josh Johanning
date: 2022-06-28 16:00:00 -0500
description: test
categories: [Test, Test2]
tags: [Test, Test2]
img_path: /assets/screenshots/2022-06-28-my-post
image:
  src: my-screenshot.png
  width: 100%
  height: 100%
  alt: my-screenshot of something
---

## Overview

...
```

### Expected behavior

Preview image should still be there

### Screenshots

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/19912012/176342592-f3acb664-e3dd-4e6e-b753-24c629ed5a43.png">

### Environment

| Command                           | Version |
|-----------------------------------|---------|
| `ruby -v`                         |         |
| `gem -v`                          |         |
| `bundle -v`                       |         |
| `bundle exec jekyll -v`           |         |
| `bundle info jekyll-theme-chirpy` |         |
