### ISSUE TITLE
Images could be found

### ISSUE THREAD

**Issue by T13nn3s** [cotes2020/jekyll-theme-chirpy#864]
## Checklist

- [X] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [X] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [X] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [ ] My question is based on the latest code of the `master` banch.

## Description

For some reason, my images are not being shown correctly anymore. My pictures are hosted on a CDN, and I specified the CDN URL in the `_config.yml` file. This is what it shows on the webpage:

<img width="915" alt="Scherm­afbeelding 2023-01-18 om 19 51 03" src="https://user-images.githubusercontent.com/29333776/213268858-4926492f-164f-4ca5-9505-19c651391483.png">

In the source code this is visible:

<img width="1674" alt="Scherm­afbeelding 2023-01-18 om 19 51 28" src="https://user-images.githubusercontent.com/29333776/213268907-083c342a-631f-420c-9c83-fc377ab51b75.png">

This is my frontmatter:

```
---
layout: post
title: Hack The Box Write-Up Shoppy - 10.10.11.180
author: T13nn3s
date: 2023-01-14 20:00:00 +0100
categories: [Hack The Box, Linux]
tags: [machine, linux, write-up]
math: true
mermaid: true
image:
  src: /hackthebox/machines/shoppy/HackTheBox%20Shoppy%20Write-Up%20by%20T13nn3s.png
  width: 775
  height: 450
---
```

This is what I have specified in my `_config.yml`:

```
theme_mode:   # [light|dark]

# The CDN endpoint for images.
# Notice that once it is assigned, the CDN url
# will be added to all image (site avatar & posts' images) paths starting with '/'
#
# e.g. 'https://cdn.com'
img_cdn: 'https://cdn.binsec.nl'

# the avatar on sidebar, support local or CORS resources
```

# What I had tried?

I tried to update my website from version 5.1.0 to 5.4.0 by editing the `Gemfile` and replacing the files with the updated ones; from that moment, everything was broken. So, I've reverted the upgrade by removing everything and cloned my Github repo with the files. This GitHub repo is a private one and the website is running on Cloudflare. The website is still working, but when I update the site the images are broken. 

# My environment:

`ruby -v` => ruby 2.7.7p221 (2022-11-24 revision 168ec2b1e5) [x86_64-darwin22]
`gem -v` => 3.3.26
`bundle -v` => Bundler version 2.3.26
`bundle exec jekyll -v` => jekyll 4.3.1
`bundle info jekyll-theme-chirpy` => jekyll-theme-chirpy (5.4.0) 

For some reason, the bundle info shows the latest version of the theme. Is this maybe the problem? Can someone help me with this?

Thanks in advance!!
