### ISSUE TITLE
sidebar.html rel="me' adds both noopener and me to the mastodon href

### ISSUE THREAD

**Issue by ebmarquez** [cotes2020/jekyll-theme-chirpy#875]
## Checklist

- [x] I have read the [tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I found the bug on the latest code of the `master` branch.

## Describe the bug
sidebar.html rel="me' adds both noopener and me to the mastodon href

```html
      {% if url %}
      <a href="{{ url }}" aria-label="{{ entry.type }}"
        {% assign link_types = nil %}
        {% unless entry.noblank %}
          {% assign link_types = link_types | append: " noopener" %}
          target="_blank"
        {% endunless %}

        {% if entry.type == 'mastodon' %}
          {% assign link_types = link_types | append: " me" %}
        {% endif %}

        {% if link_types %}rel="{{ link_types | lstrip }}"{% endif %}>
        <i class="{{ entry.icon }}"></i>
      </a>
```
Mastodon rel=me is not generating correctly.  Expected output is rel=" me" but in the generated code I see 
`<a href="https://twit.social/@ebmarquez" aria-label="mastodon" target="_blank" rel="noopener me">`

### To Reproduce
view-source:https://ebmarquez.github.io//

Edit the following template:
**/workspaces/ebmarquez.github.io/_data/contact.yml**

updated type: mastodon with the required fields

```yaml
# Uncomment and complete the url below to enable more contact options
-
   type: mastodon
   icon: 'fab fa-mastodon'   # icons powered by <https://fontawesome.com/>
   url:  'https://twit.social/@ebmarquez'                  # Fill with your Mastodon account page, rel="me" will be applied for verification
```

Generated code shows: 
`<a href="https://twit.social/@ebmarquez" aria-label="mastodon" target="_blank" rel="noopener me">`

### Screenshots
![image](https://user-images.githubusercontent.com/15785107/216693355-055abf22-3259-4db4-a682-82c2733913ab.png)

### Environment

| Command                           | Version |
|-----------------------------------|---------|
| `ruby -v`                         |         |
| `gem -v`                          |         |
| `bundle -v`                       |         |
| `bundle exec jekyll -v`           |         |
| `bundle info jekyll-theme-chirpy` |         |

### Desktop

- Browser: Edge Version 111.0.1652.0 (Official build) dev (64-bit)
