### ISSUE TITLE
How can I change the highlight CSS ?

### ISSUE THREAD

**Issue by devl00p** [cotes2020/jekyll-theme-chirpy#907]
## Description

I'd like to try different highlight themes for Rouge but my modifications t(o the `_config.yml `files doesn't seem to have any effect

## Operations you have already tried

I took some CSS from this project : https://github.com/brazacz/rouge-themes

I copied the CSS files to /assets/css/

I changed the `kramdown` section of the `_config.yml` file to add a `css_path` entry :

```yaml
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    css_path: /assets/css/tulip.css
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
```

When I regenerate/serve the website again with `bundle exec jekyll s` I can't notice any difference in code highlighting (tested with several themes)

What can I do to correctly use another CSS file for code highlighting ?

Regards
