### ISSUE TITLE
Properly set the Google Pageviews

### ISSUE THREAD

**Issue by ArihantB** [cotes2020/jekyll-theme-chirpy#92]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## I don't understand what the ReadMe/Wiki says

I checked out your blog to set up Google Pageviews, but after the part where we get the endpoint URL, it gets confusing.
I then changed the _config.yml to following:
```
id: 'UA-65297873-3'          # Fill with your Google Analytics ID
    pv:
    # The Google Analytics pageviews switch.
    # DO NOT enable it unless you know how to deploy the Google Analytics superProxy.
    enabled: true
    # the next options only valid when `google_analytics.pv` is enabled.
    proxy_url: ''
    proxy_endpoint: 'https://model-axe-250517.appspot.com/query?id=ahJqfm1vZGVsLWF4ZS0yNTA1MTdyFQsSCEFwaVF1ZXJ5GICAgOjXh4EKDA'
    cache: true
```

Then I build.sh -> init.sh -> run.sh.
I am running it on localhost. There is a spinner beside the eye-icon.
![image](https://user-images.githubusercontent.com/16287025/88374618-a1791e00-cdb7-11ea-8d95-0735581dc24c.png)

The javascript for pageviews is blocking other scripts from running, i.e. scripts for TOC, back-to-top are not working.

Also, in your `pageviews.js` file, the method `fetchProxyPageviews()` requires a `_pageviews.json` file which is no where to be found. So I made one myself and put the content of the `endpoint_url` in it.

It stopped giving errors but it doesn't seem to be working.

It would be very nice if you can explain how to setup those variables in _config.yml or what to do after the part when we get the endpoint_url from Google Analytics superProxy. I went through your blog post many times, but still I am unable to get it working. Help please, I think I am lost.

**Comment by cotes2020** [comment]
So far, there is no detailed tutorial of how to configure and use the pageviews display because it is too complicated and unnecessary for most people. In addition, if the number of pageviews is too low, it may undermine the author's enthusiasm for writing.

I appreciate your perseverance to explore the configuration of the PV part, now I will briefly introduce how to configure it:

```yml
# Change to your Google Analytics ID
google_analytics:
  id: 'UA-65297873-3'
  pv:
    enabled: true
    proxy_url: 'https://model-axe-250517.appspot.com'  # the URL of proxy_endpoint
    proxy_endpoint: 'https://model-axe-250517.appspot.com/query?id=ahJqfm1vZGVsLWF4ZS0yNTA1MTdyFQsSCEFwaVF1ZXJ5GICAgOjXh4EKDA'
    cache: false  # pv data local cache, good for the users from GFW area.
```

In this way, your website should be able to display PV reports.

The option `cache` is to specify whether to store a copy of PV reports in your repo (because in some areas, such as China, visitors to your website will not be able to access GAE, and the cache of the PV can temporarily replace GAE response data), if you enable this option, then please save the response content of `proxy_endpoint` as the file `/assets/js/data/_pageviews.json`:

```console
$ cd /the/root/directory/of/your/repo/

$ export PROXY_URL="https://model-axe-250517.appspot.com/query?id=ahJqfm1vZGVsLWF4ZS0yNTA1MTdyFQsSCEFwaVF1ZXJ5GICAgOjXh4EKDA"
$ wget $PROXY_URL -O assets/js/data/_pageviews.json
```

> In fact, if you don't write a Chinese blog, you can ignore this.
