### ISSUE TITLE
YouTube Button 

### ISSUE THREAD

**Issue by iis2h** [cotes2020/jekyll-theme-chirpy#947]
How can I add YouTube button Linked to my youtube channel to Social Accounts that displayed on sidebar

**Comment by gastongc** [comment]
You need to add a new entry to `_data/contact.yml`

```yaml
-
  type: youtube
  icon: 'fab fa-youtube'
  url: 'https://youtube.com/YOUR_CHANNEL'
```

You can add also other links and assign it an icon by using that template, just check on [FontAwesome icons](https://fontawesome.com/search?m=free&o=r) and copy the `fa-<code>` into icon property, but do not remove `fab`
