### ISSUE TITLE
Make rounded corner images

### ISSUE THREAD

**Issue by v4vong** [cotes2020/jekyll-theme-chirpy#960]
## Describe the solution you'd like

Make images in a post be rounded-corner. It will make them look better. We can let this be the default, or provide a class, e.g.

```markdown
![example](example.png){: .round }
```

**Comment by cotes2020** [comment]
Check out the Bootstrap docs, there are a bunch of rounded classes you'll like :)

**Comment by v4vong** [comment]
> Check out the Bootstrap docs, there are a bunch of rounded classes you'll like :)

OK, thanks. I'll check.

**Comment by danielmacuare** [comment]
I was looking at how to do this as I don't know much about Frontend. I'll leave my solution here in case it helps someone else

**Theme Instructions (Have a read at this first):** https://chirpy.cotes.page/posts/getting-started/#customizing-stylesheet


The way I did this was:
- Adding 2 files: https://github.com/danielmacuare/danielmacuare.github.io/commit/cd7c960defba62d7322bf951820899d9468a578f
- Adding a border Radius to the Post images: https://github.com/danielmacuare/danielmacuare.github.io/commit/f09d0dc60601c6c1ef8e539ba52058967a7c182a

You can then see the round borders for all the images added to each post.

**Example:** https://blog.dmac.tech/posts/boto3-code-completion/

**Comment by v4vong** [comment]
Just directly use `{: .rounded }`. It is defined in Bootstrap.

**Comment by danielmacuare** [comment]
Nice, thanks for the suggestions, that's defo way easier. How would I go about setting properties to this one? I've tried googling but I can't find a way to do it.

I'd like to modify the border-radius to a specific value. Something like this:

`{: .rounded border-radius:.60rem; }` --> I'm just making this out. I tried this and wouldn't work

**Comment by v4vong** [comment]
For example, create a CSS file in your repo:

`assets/css/border-radius.css`:

```css
.rounded-1 {
    border-radius: .2rem;
}

.rounded-2 {
    border-radius: .25rem;
}

.rounded-3 {
    border-radius: .3rem;
}

.rounded-4 {
    border-radius: .35rem;
}

.rounded-5 {
    border-radius: .4rem;
}

.rounded-6 {
    border-radius: .45rem;
}

.rounded-7 {
    border-radius: .5rem;
}

.rounded-8 {
    border-radius: .55rem;
}

.rounded-9 {
    border-radius: .6rem;
}
```

On the page you want to apply these predefined classes, you need to import this file first:

```html
<link rel="stylesheet" href="{{ 'assets/css/border-radius.css' | relative_url }}">
```

Then you can specify the border-radius of any element on this page, e.g. `{: .rounded-9 }`.

But this method looks a little ugly. There may be more elegant ways.
